# .github/workflows/save-handlowcy.yml

name: Sync handlowcy.tmp.json to handlowcy.json

on:
  push:
    paths:
      - 'handlowcy.tmp.json'

jobs:
  update-main-handlowcy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Move handlowcy.tmp.json to handlowcy.json
        run: |
          cp handlowcy.tmp.json handlowcy.json

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add handlowcy.json
          git commit -m "🔁 Sync handlowcy.tmp.json to handlowcy.json"
          git push
