---
name: Save Handlowcy from PR

on:
  push:
    branches:
      - main
    paths:
      - 'handlowcy.tmp.json'

jobs:
  update-handlowcy-json:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Copy temp to real json
        run: |
          cp handlowcy.tmp.json handlowcy.json

      - name: Commit and push updated handlowcy.json
        run: |
          git config user.name "AutoBot"
          git config user.email "action@github.com"
          git add handlowcy.json
          git commit -m "Aktualizacja handlowców z PR" || echo "Brak zmian"
          git push
